#Done
#v1.0

import time

print("Welcome, User!")
print(" ")
print("Let's create your biography!")
time.sleep(1)
print("----------------------------")
print("👨👩👦 Personal information:")
print(" ")
print("Firstly:")
user_name = input("please, write your first name, last name - ")
time.sleep(1)
print(" ")
print("Secondly:")
age = int(input("please, write your age - "))
time.sleep(1)
print(" ")
print("Thirdly: ")
place_living = input("please, write where you live - ")
time.sleep(1)
print(" ")
print("Forthly: ")
gender = input("please, write what gender you are - ")
print("Thank's")
print("----------------------------")
time.sleep(1)
print("💡🛠️🌟 Skills and interests:")
print(" ")
print("💡🛠️ Firstly - skills!")
print(" ")
languages = input("please write which languages ​you speak - ")
print(" ")
technical_skills = input("please also write your technical skills - ")
print(" ")
time.sleep(1)
print("🌟🎯 Now - interests!")
print(" ")
hobby = input("please write your hobby - ")
print(" ")
favorite_book = input("please write your favorite book - ")
print(" ")
favorite_movie = input("please write your favorite movie - ")
print(" ")
dream = input("please write your dream or life goal - ")
print("Thank's!")
time.sleep(1)
print("🔍 Analyzing your answers...")
time.sleep(2.5)
print("🛠️ Creating biography...")
time.sleep(2.5)
print(" ")
print(" ")
print(" ")
print(" ")
print("------------------- Biography -------------------")
print("👨👩👦 Personal information:")
print(" ")
print(f"{user_name}.")
print(f"{age} - years old.")
print(f"Gender - {gender}.")
print(f"Living in {place_living}.")
print("--------------------------------------------------")
print("💡🛠️🌟 Skills and interests:")
print(" ")
print("💡🛠️ Skills:")
print(f"Speaks {languages}!")
print(f"Technical skills - {technical_skills}!")
print(" ")
print("🌟🎯 Interests:")
print(f"Dream - {dream}!")
print(f"Hobby - {hobby}!")
print(f"Favorite book - {favorite_book}!")
print(f"Favorite movie - {favorite_movie}!")
print("--------------------------------------------------")