#done!

print("----------------------------------------------")
print("-----------Create Hero Card-------------------")
print("----------------------------------------------")
nameofhero = input("Enter Hero Name: ")
powerofhero = input("Enter Hero Power: ")
ageofhero = int(input("Enter Hero Age: "))
print("----------------------------------------------")
print("-------------Hero Card Created----------------")
print("----------------------------------------------")
print("-------------Hero Card:-----------------------")
print("----------------------------------------------")
print(f"Hero Name: {nameofhero}")
print(f"Hero Power: {powerofhero}")
print(f"Hero Age: {ageofhero}")
print("----------------------------------------------")