print("Welcome to the Roblox!")
print("----------------------")
print("First, you need to create your account to play the game!")
print("----------------------")
username = input("Enter your username: ").capitalize()
password = input("Enter your password: ")
while len(password) < 8:
    print("Password must be at least 8 characters long. Please try again.")
    password = input("Enter your password: ")
print(f"Congratulations {username}, your account has been created successfully!")
print("----------------------")
print("Sorry, we have technical issues with our servers. Please can you log in?")
print("----------------------")
login_username = input("Enter your username: ").capitalize()
while login_username != username:
    print("Incorrect username. Please try again.")
    login_username = input("Enter your username: ").capitalize()
print("Username is correct.")
login_password = input("Enter your password: ")
while login_password != password:
    print("Incorrect password. Please try again.")
    login_password = input("Enter your password: ")
print("Password is correct.")
print(f"Welcome back, {username}!")