#done!

print("Welcome to the Portfolio Program!")
print(" ")
print("This program will ask for your name and age, and then some information for your portfolio.")
print(" ")
print("Let's get started!")
print(" ")
print("Create a portfolio to showcase your skills and achievements!")
print(" ")
print("Please enter the following information:")
print(" ")
Name = input("Enter your name: ")
print(" ")
Age = int(input("Enter your age: "))
print(" ")
if Age < 0:
    print("Age cannot be negative.")
elif Age < 18:
    print("You are a kid.")
elif Age >= 18 and Age < 65:
    print("You are an adult.")
else:
    print("You are a senior.")
print(" ")
print(f"Hello, {Name}! You are {Age} years old.")
print(" ")
print("Now, let's add some information to your portfolio.")
print(" ")
Skills = input("Enter your skills (separated by commas): ")
print(" ")
Achievements = input("Enter your achievements (separated by commas): ")
print(" ")
print("Your Portfolio:")
print(f"Name: {Name}")
print(f"Age: {Age}")
print(f"Skills: {Skills}")
print(f"Achievements: {Achievements}")
print(" ")
print("Thank you for using the Portfolio Program! Goodbye!")